package stree;

public enum Tag { 
    AFF("="), 
    NOT("!"), 
    AND("&&"), 
    OR("||"), 
    LT("<"), 
    GT(">"), 
    LE("<="), 
    GE(">="), 
    EQ("=="), 
    DIFF("!=") , 
    PLUS("+"), 
    MINUS("-"), 
    MINUS_U ("-"), 
    CIRCON("^"),
    MULT("*"), 
    DIV("/"), 
    PLUSEQ("+="),
    MINUSEQ("-="),
    MOD("%"),
    LSHIFT("<<"),
    RSHIFT(">>"),
    INC("++"),
    DEC("--"),
    TILDE("~"),
    STAR("*"),
    AMPER("&"),
    PIPE("|"),
    DOT("."),
    ARROW("->"),
    SUCC("SUCC"),
    PRODUCT("PRODUCT"),
    IDENTIFIER("IDENTIFIER"),
    FCTCALL("FCTCALL"),
    LISTOF("LISTOF"),
    POINTER("POINTER"),
    CHARACTER("CHARACTER"), 
    INTEGER("INTEGER"), 
    FLOAT("FLOAT"), 
    STRING("STRING"),
    BOOL("BOOL"),
    CLASS("CLASS"),
    STATIC("STATIC"),
    NAME("NAME"),
    NB("NB"),
    EXP("EXP"),
    TYPE("TYPE"),
    BODY("BODY"),
    ARRAY("ARRAY"),
    VARDEF("VARDEF"),
    HEXA("HEXA"),
    TRUE("TRUE"),
    FALSE("FALSE"),
    NULL("NULL"),
    VOID("VOID"),
    RETURN("RETURN"),
    STOP("STOP"),
    BREAK("BREAK"),
    STRUCT("STRUCT"),
    IF("IF"),
    IFELSE("IFELSE"),
    ELSE("ELSE"),
    WHILE("WHILE"), 
    FOREACH("FOREACH"),
    REPEAT("REPEAT"),
    IN("IN"),
    THENELSE("THENELSE"),
    STATEMENT("STATEMENT"),
    BLOCK("BLOCK"),
    FUNCDEF("FUNCDEF"),
    PROTOTYPE("PROTOTYPE"),
    FUNCPARAMS("FUNCPARAMS"),
    PARAM("PARAM"),
    RETURNTYPE("RETURNTYPE"),
    VARDEC("VARDEC"),
    STRUCTFIELDS("STRUCTFIELDS"),
    ERROR("ERROR"),
    NBLIST("NBLIST"),
    PARAMSLIST("PARAMSLIST"),
    ARGSLIST("ARGSLIST"),
    EMPTYBLOCK("EMPTYBLOCK"),
    ACCESSOR("ACCESSOR"),
    ACCESSIBLE("ACCESSIBLE"),
    ARRAYACCESSOR("ARRAYACCESSOR"),
    INDEX("INDEX");

    private final String tag;

    Tag(String s) {
    	tag = s;
    }

    public String toString() {
    	return tag;
    }
}

